apiVersion: apps/v1
kind: Deployment
metadata:
  name: testfile-deployment
  labels:
    app: testfile
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testfile
  template:
    metadata:
      labels:
        app: testfile
    spec:
      containers:
        - name: testfile
          image: aravind200431/testfile:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8088
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
