apiVersion: v1
kind: Service
metadata:
  name: testfile-service
spec:
  type: NodePort
  selector:
    app: testfile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
      nodePort: 30080
